apiVersion: v1
kind: Template
metadata:
  name: vault-manager
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: vault-manager
    name: vault-manager
  spec:
    replicas: ${{REPLICAS}}
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    selector:
      matchLabels:
        app: vault-manager
    template:
      metadata:
        labels:
          app: vault-manager
      spec:
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: vault-manager
          env:
            - name: GRAPHQL_QUERY_FILE
              value: ${GRAPHQL_QUERY_FILE}
            - name: GRAPHQL_SERVER_URL
              value: ${GRAPHQL_SERVER_URL}
            - name: GRAPHQL_USERNAME
              value: ${GRAPHQL_USERNAME}
            - name: GRAPHQL_PASSWORD
              value: ${GRAPHQL_PASSWORD}
            - name: GRAPHQL_QUERY_FILE
              value: ${GRAPHQL_QUERY_FILE}
            - name: VAULT_ADDR
              value: ${VAULT_ADDR}
            - name: VAULT_AUTHTYPE
              value: ${VAULT_AUTHTYPE}
            - name: VAULT_ROLE_ID
              value: ${VAULT_ROLE_ID}
            - name: VAULT_SECRET_ID
              value: ${VAULT_SECRET_ID}
          resources:
            requests:
              memory: ${MEMORY_REQUESTS}
              cpu: ${CPU_REQUESTS}
            limits:
              memory: ${MEMORY_LIMIT}
              cpu: ${CPU_LIMIT}

parameters:
- name: IMAGE
  value: quay.io/app-sre/vault-manager
  displayName: vault-manager image
  description: vault-manager docker image. Defaults to quay.io/app-sre/vault-manager
- name: IMAGE_TAG
  value: latest
  displayName: vault-manager version
  description: vault-manager version which defaults to latest
- name: MEMORY_REQUESTS
  value: 200Mi
- name: MEMORY_LIMIT
  value: 300Mi
- name: CPU_REQUESTS
  value: 250m
- name: CPU_LIMIT
  value: 500m
- name: REPLICAS
  value: '1'